### ISSUE TITLE
Why all codes are in txt format?

### ISSUE THREAD

**Issue by duguyue100** [PuzzlesLab/UVA#1]
Somehow I browse over this repo since it showed up in my updates.
So, why all java codes are all in txt format?

**Comment by rayson1223** [comment]
Good question, I wonder why need a bash script as well.. lol

**Comment by kingkingyyk** [comment]
i c'n'p my code to notepad and save. voila! :dart:

**Comment by rayson1223** [comment]
It is suppose to submit as java file bro @kingkingyyk  ._.
